name: Run Test Suite

on:
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    name: All tests
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Test code with pytest
      run: |
        python3 -m venv venv
        . ./venv/bin/activate
        pip install .[dev]
        ./venv/bin/py.test tests/ -s -v --durations 0
